// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Sign and Says",
    platforms: [
        .iOS("18.1")
    ],
    products: [
        .iOSApplication(
            name: "Sign and Says",
            targets: ["AppModule"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .heart),
            accentColor: .presetColor(.mint),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .photoLibraryAdd(purposeString: "Please allow access to photos so you can create picture icons for your child!"),
                .camera(purposeString: "Please allow us to take pictures of new icons and live record sign language in real time."),
                .microphone(purposeString: "Please allow us to recognize you or your child’s voice."),
                .photoLibrary(purposeString: "Please allow access to your photos to create new picture icons for your child."),
                .speechRecognition(purposeString: "Please allow us to recognize you or your child’s voice.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)